### ISSUE TITLE
falling back to JSON fails

### ISSUE THREAD

**Issue by mrgleeco** [signalfx/signalfx-python#100]
using the client v1.1.5 getting this error :

```
Protocol Buffers not installed properly; falling back to JSON.
Posting data to SignalFx failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/signalfx/ingest.py", line 244, in _send
    self._INGEST_ENDPOINT_DATAPOINT_SUFFIX))
  File "/usr/local/lib/python3.7/site-packages/signalfx/ingest.py", line 266, in _post
    data = c.compress(data) + c.flush()
TypeError: a bytes-like object is required, not 'str' 
```
could repro by running `pip uninstall protobuf` and sending an otherwise good metric payload.

**Comment by mpetazzoni** [comment]
@mrgleeco Thanks for reporting! This is fixed in v1.1.6.
