### ISSUE TITLE
Python 3: ImportError: No module named 'constants'

### ISSUE THREAD

**Issue by jtprobst** [signalfx/signalfx-python#30]
On a host running Ubuntu 14.04 (Python 3.4) I installed signalfx using
`pip3 install signalfx`

However when trying to use it, i get an ImportError.
```
$ python3
Python 3.4.3 (default, Sep 14 2016, 12:36:27) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import signalfx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/signalfx/__init__.py", line 45, in <module>
    from constants import DEFAULT_API_ENDPOINT, DEFAULT_INGEST_ENDPOINT, \
ImportError: No module named 'constants'
```

The same happens inside a Docker container when performing the following steps
```
$ docker pull python
[...]
$ docker run -it python bash
root@964bb9e12c78:/# pip3 install signalfx
[...]
root@964bb9e12c78:/# python
Python 3.5.2 (default, Sep 24 2016, 05:23:05) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import signalfx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/signalfx/__init__.py", line 45, in <module>
    from constants import DEFAULT_API_ENDPOINT, DEFAULT_INGEST_ENDPOINT, \
ImportError: No module named 'constants'

```

**Comment by mpetazzoni** [comment]
Right on cue :) Just started working on Python 3 compatibility fixes this week. See #29. Thanks!

**Comment by jtprobst** [comment]
Awesome, you're a life saver! Thanks :)

**Comment by jtprobst** [comment]
I saw that #29 was merged and tested it by running
```pip3 install git+https://github.com/signalfx/signalfx-python```

Now I get the following error:
```
root@682c4a5e1844:/# python
Python 3.5.2 (default, Sep 24 2016, 05:23:05) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import signalfx
>>> signalfx.SignalFx().ingest("asdf")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/signalfx/__init__.py", line 98, in ingest
    from . import ingest
  File "/usr/local/lib/python3.5/site-packages/signalfx/ingest.py", line 16, in <module>
    from .generated_protocol_buffers \
  File "/usr/local/lib/python3.5/site-packages/signalfx/generated_protocol_buffers/signal_fx_protocol_buffers_pb2.py", line 111, in <module>
    has_default_value=False, default_value=unicode("", "utf-8"),
NameError: name 'unicode' is not defined
```
